### PR TITLE
Added 'selected' option to Legend

### PR DESCRIPTION
**Pull request by CAPCHIK**
In V2 G2Plot exist option `legendOption.selected`

https://g2plot.antv.vision/en/docs/api/plots/line#legendoptionselected--

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-charts-blazor?pullRequest=47) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-charts-blazor?pullRequest=47) before we can accept your contribution.<br/><br/>:x: CAPCHIK [sign now](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-charts-blazor?pullRequest=47)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/ant-design-blazor/ant-design-charts-blazor?pullRequest=47) it.</sub>

**Comment by ElderJames** [comment]
Thanks for contribution @CAPCHIK .

**Comment by Henxun** [comment]
why its not work

**Comment by CAPCHIK** [comment]
> why its not work

Can you show, how you use it?

**Comment by Henxun** [comment]
屏幕截图 2021-11-16 224458
like this

**Comment by Henxun** [comment]
> > why its not work
> 
> Can you show, how you use it?
>
>just like this
屏幕截图 2021-11-16 224458

**Comment by CAPCHIK** [comment]
@Henxun You should use XField value for key

On screenshot you are use `1`, from `type`, but `XField` binds to `year`.

Try to use `{ "1998", false }`

**Pull request merged**
