### PR TITLE
fix: Added AutoFit

### PR DESCRIPTION
**Pull request by superjerry88**
- Fix issue where shrinking the docs will not reset the width to smaller size
- Fix width config not applying effect (https://github.com/ant-design-blazor/ant-design-charts-blazor/issues/44)
- Milestone (https://github.com/ant-design-blazor/ant-design-charts-blazor/issues/100)

### CODE REVIEW

**Comment by superjerry88** [comment]
According to V2 changelog, ForceFit is replaced by AutoFit. 

Which approach should we take to apply this ? 
1) Use obsolete tag
2) Remove it completely (breaking change)
3) Remain as it is

**Comment by ElderJames** [comment]
Thanks for contribution @superjerry88 ! I think it's better to use the obsolete attribute.

**Comment by superjerry88** [comment]
@ElderJames Added absolute attribute and fixed warnings related to it. Ready for merge :)

**Comment by ElderJames** [comment]
@superjerry88 Thank you!

**Pull request merged**
