### PR TITLE
fix: G2Plot 2.0 Migration

### PR DESCRIPTION
**Pull request by superjerry88**
### Chart Components: 
- **All Plot**
	- Obsoleted 'Guideline'. replaced with `Annotation`
	- Obsoleted 'Title'
	- Obsoleted 'Description'
- **HeatMap** 
	- Added `Density Type`
- **Area**
	- Added `Slider`
	- Added `ScrollBar`
- **Bar** 
	- Added `Slider`
	- Added `ScrollBar`
	- Added `IsStack`
	- Added `IsRange`
	- Added `IsPercent`
	- Added `Label.Layout`
- **Column**
	- Added `Slider`
	- Added `ScrollBar`
	- Added `IsStack`
	- Added `IsRange`
	- Added `IsPercent`
	- Added `Label.Layout`
- **DualAxes**
	- Added `Slider`
	- Added `ScrollBar`
- **Line** 
	- Added `Slider `
	- Added `ScrollBar`
- **Stock**
	- Added `Slider`
- **Scatter**
	- Obsoleted `pointSize`, replaced with `Size`
	- Obsoleted `trendLine`, replaced with `RegressionLine`
- **Gauge**
	- Obsoleted `Min`
	- Obsoleted `Max`
	- Obsoleted `color`
	- Added `Radius`
	- Added `InnerRadius`
	- Updated `Range`
	- Added `Indicator`
	- Added `GaugeStyle`
	- Added `Type`
- **Liquid**
	- Obsoleted `Min`
	- Obsoleted `Max`
	- Added `Shape`
	- Added `Wave`
	- Added `Outline`
	- Added `Pattern`
- Obsoleted 'DensityHeatmap'. replaced with `Heatmap`

### Demo: 
- Removed all usage of 'Title' 
- Removed all usage of 'Description'
- Updated all usage of 'Guideline' with 'Annotation' 
- Updated DensityHeapMap Chart
- Updated Stock Chart 
	- Stock plot with slider
- Updated Area Chart 
	- Basic area plot
	- Gradient Area Plot
	- Area Plot With Slider
	- Basic Area Plot With Line Annotation
- Updated Line Chart
	- Basic line Plot
	- Basic spline plot
	- Set style of line plot point
	- Line plot with slider
	- Line plot with regionFilter
- Updated Column Chart
	- Column plot with slider
	- Column plot with scrollbar
- Updated Bar Chart
	- Basic bar plot
	- Bar plot column width (wip)
	- Bar plot with customize width (wip)
	- Bar chart with scrollbar
	- Bar plot conversion tag
	- Bar plot with background
- Updated Ranged Bar Chart
- Updated Stacked Bar Chart
- Updated Percent Stacked Column Chart
- Updated Ranged Column Chart
- Updated Stacked Column Chart
- Updated Bubble Chart
- Updated Scatter Chart
- Updated Gauge Chart 
	- Basic gauge plot
	- Set range width of gauge
	- Gradient gauge plot
	- Gauge plot with custom color
	- Meter gauge plot
- Updated Liquid Chart
	- Liquid plot
	- Liquid plot - rect shape
	- Liquid plot - diamond shape
	- Liquid plot with pattern
- Added Column Line Chart 
- Added Stacked Column Line Chart 
- Added Grouped Coumn Line Chart 

### Extra: 
- Fixed all CS0108 warning

### CODE REVIEW

**Comment by superjerry88** [comment]
Temporary closing this PR as more changes are being made in the branch

**Comment by superjerry88** [comment]
@ElderJames . I have updated the description for all the changes, this is now ready for merge now, please have a check 😄  

Only these 2 is not updated: 
1) WordCloud - Not implemented yet
2) Bullet - Updating this will introduce breaking change

**Comment by ElderJames** [comment]
@superjerry88 Excellent!

**Comment by ElderJames** [comment]
@superjerry88 The next step is to refine the documentation before releasing the version. I haven't decided what to do yet. Do you have any suggestions?

**Comment by superjerry88** [comment]
@ElderJames  unfortunately I don't have much idea how we can approach this. I only tried to to match the current example demo to the source as much as i can (https://charts.ant.design/en/examples/line/basic#line) 

Im happy to help once you've laid out some groundwork though 😄

**Pull request merged**
