### PR TITLE
Added Box and Violin chart.

### PR DESCRIPTION
**Pull request by MaggiGorengAyam**
Based on [Ant Design Charts](https://charts.ant.design/en/examples/more-plots/box#basic).
Please note that we can't read Chinese, so the `menu.json` needs some proofreading.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-charts-blazor?pullRequest=97) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-charts-blazor?pullRequest=97) before we can accept your contribution.<br/><br/>:x: MaggiGorengAyam [sign now](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-charts-blazor?pullRequest=97)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/ant-design-blazor/ant-design-charts-blazor?pullRequest=97) it.</sub>

**Comment by MaggiGorengAyam** [comment]
Added [Violin chart](https://charts.ant.design/en/examples/more-plots/violin#basic).

**Comment by ElderJames** [comment]
Thanks for contribution! We've been waiting for someone to do that for a long time!  I hope you can help solve some bugs mentioned in the issues.

**Comment by superjerry88** [comment]
Happy to hear that, we will be looking into some of the issues as well 😎

**Comment by ElderJames** [comment]
Thank you very much @superjerry88 ! And we don't seem to support event callbacks yet, can you help implement them?

**Comment by superjerry88** [comment]
@ElderJames currently we are planning to bring in more charts and fixed some of the outdated config like annotation first. Our current understanding of G2Plot is still limited, if you any suggestion or idea on how we can tackle the callback then it will be helpful to kickstart our implementation.

**Comment by ElderJames** [comment]
Ok, let's merge this PR first and discuss it in another issue.

**Pull request merged**
